# Server Configuration
server.port=${SERVER_PORT:8087}
server.servlet.context-path=/

# Spring Application Name
spring.application.name=notification-service

# MongoDB Configuration
spring.mongodb.host=${SPRING_MONGODB_HOST:localhost}
spring.mongodb.port=${SPRING_MONGODB_PORT:27017}
spring.mongodb.database=${SPRING_MONGODB_DATABASE:notification_db}
spring.mongodb.username=${SPRING_MONGODB_USERNAME:}
spring.mongodb.password=${SPRING_MONGODB_PASSWORD:}
spring.mongodb.authentication-database=${SPRING_MONGODB_AUTHENTICATION_DATABASE:admin}
spring.data.mongodb.auto-index-creation=true

# Add any other necessary properties here
