server.port=8085
server.servlet.context-path=/
server.error.include-stacktrace=never
server.error.include-exception=false

spring.application.name=payment-service
spring.mongodb.uri=${MONGO_URI}

payment.gateway.provider=stripe-test
payment.currency=${PAYMENT_CURRENCY}
payment.minimum-amount=${PAYMENT_MINIMUM_AMOUNT}
payment.maximum-amount=${PAYMENT_MAXIMUM_AMOUNT}
payment.stripe.secret-key=${STRIPE_SECRET_KEY}
payment.stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET}
payment.frontend-base-url=${FRONTEND_BASE_URL}
payment.stripe.success-url=${payment.frontend-base-url}/patient/payment?appointment_id={APPOINTMENT_ID}&checkout=success
payment.stripe.cancel-url=${payment.frontend-base-url}/patient/payment?appointment_id={APPOINTMENT_ID}&checkout=cancel

services.appointment.url=${SERVICES_APPOINTMENT_URL}
services.notification.url=${SERVICES_NOTIFICATION_URL}

logging.level.com.medilink.paymentservice=DEBUG
