server.port=8084
server.servlet.context-path=/api

spring.application.name=appointment-service
spring.mongodb.uri=${MONGO_URI}

services.patient.url=${SERVICES_PATIENT_URL}
services.doctor.url=${SERVICES_DOCTOR_URL}

logging.level.root=INFO
