# Server Configuration
server.port=${SERVER_PORT:8089}
server.servlet.context-path=/
server.error.include-message=always
server.error.include-binding-errors=always
server.tomcat.threads.max=100
server.tomcat.threads.min-spare=10
server.tomcat.accept-count=100

# Spring Application Name
spring.application.name=ai-symptom-checker-service

# MongoDB Configuration
spring.mongodb.host=${SPRING_MONGODB_HOST:localhost}
spring.mongodb.port=${SPRING_MONGODB_PORT:27024}
spring.mongodb.database=${SPRING_MONGODB_DATABASE:ai_symptom_db}
spring.mongodb.username=${SPRING_MONGODB_USERNAME:}
spring.mongodb.password=${SPRING_MONGODB_PASSWORD:}
spring.mongodb.authentication-database=${SPRING_MONGODB_AUTHENTICATION_DATABASE:admin}
spring.data.mongodb.auto-index-creation=true
# Add any other necessary properties here
